# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Copy from main to documentation branch

on:
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  deploy:
    name: Copy Markdowns
    runs-on: ubuntu-latest
    steps:
      - uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.ACTION_TOKEN  }}
          src_branch: main
          src_path: /docs/.
          dst_owner: dan-lee76
          dst_repo_name: notes
          dst_path: /docs/
          dst_branch: documentation
          clean: true
          commit_message: "Sections copied from master to documentation branch!"
